<?php



class BricFilters {
	
	
	function __construct() {
		
		$this->add_filters();
		
	}
		
	
	function add_filters() {
		
		//Add classes based on settings
		add_filter( 'body_class', array( $this, 'body_class' ), 10, 2 );

		//Wrap youtube links in responsive embed
		add_filter( 'embed_oembed_html', array( $this, 'embed_wrap'), 10, 4 );

		//prevent column shortcode plugin from outputting stylesheet
		add_filter( 'cpsh_load_styles', '__return_false', 100 );
		
		//Exclude BRIC Assets that are minified to be sent to WP Offload minifying
		add_filter( 'as3cf_minify_exclude_files', array( $this, 'as3cf_minify_exclude_files' ) ); 

		
		// Force Gravity Forms to init scripts in the footer and ensure that the DOM is loaded before scripts are executed
		add_filter( 'gform_init_scripts_footer', '__return_true' );
		add_filter( 'gform_cdata_open', array( $this, 'wrap_gform_cdata_open' ), 1 );
		add_filter( 'gform_cdata_close', array( $this, 'wrap_gform_cdata_close' ), 100 );
	
	
	
		//Auto-populate ALT tags with title/caption text if not available
		//apply_filters( 'wp_get_attachment_image_attributes', $attr, $attachment, $size );
		add_filter( 'wp_get_attachment_image_attributes', [ $this, 'image_alt_tag'], 10, 3 );
	}
	
	
	/**
	 *		Filter body classes for site sizes
	 *		and use CSS to control
	 *
	 */
	
	function body_class( $classes, $additional_classes ) {
		
		global $SiteInfo;
		
		
		if ( $SiteInfo->options->main_content->container ) {
			
			$classes[] = 'main-content-container';
		
		}
		
		if ( !empty( $SiteInfo->body_classes ) ) {
			
			foreach ( $SiteInfo->body_classes as $class ) {
				
				$classes[] = $class;
				
			}
			
		
		}
		
				
		
		
		//full-width image
		if ( has_post_thumbnail() ) {
			
			$classes[] = 'has-header-image';
		}
				
		return $classes;
		
	}
	
	
	
	
	/*
	 *		Wrap embed code that is auto-generated by WP for responsive YouTube
	 *		Ensure that no related videos are shown at the end.
	 *
	 *		NOTE: This only will happen on the new save of a URL from the content editor. It then will cache the iFrame markup
	 *		apply_filters( 'embed_oembed_html', mixed $cache, string $url, array $attr, int $post_ID )
	 *		
	 */

	function embed_wrap( $cache, $url, $attr, $post_id ) {


		//Find the src string in the iframe HTML
		preg_match('/src="(.+?)"/', $cache, $matches);

		
		$youtube = strpos( $matches[1], 'youtube' );
		
		if ( $youtube !== false ) {

			//Add the rel=0 parameter
			$params = array(
				'controls'    => 1,
				'hd'        => 1,
				'autohide'    => 1,
				'rel' => 0,
			);
			
		

			//Add the new parameters to the src string
			$new_url = add_query_arg($params, $matches[1] );

			//replace old src string with new one
			$cache = str_replace( $matches[1], $new_url, $cache );

			//add responsive div and return new iframe HTML
			return '<div class="embed-responsive embed-responsive-16by9">'.$cache.'</div>';
		
		}
		
		else {
			
			return $cache;
		}
		
	}


	/**
	 *		Prevent Bric theme CSS (that's already minified)
	 *		to be sent to the WP Offload Minifier
	 *
	 */
	
	function as3cf_minify_exclude_files( $exclude ) {
		
		//$exclude[] = '/abspath/wp-content/themes/twentyfifteen/genericons/genericons.css';
		
		$exclude[] =  get_stylesheet_directory().'/assets/css/bric-style.css';
		$exclude[] =  get_stylesheet_directory().'/assets/css/bric-style-customizer.css';

		
		return $exclude;
		
	}
	
	
	
	
	function wrap_gform_cdata_open( $content = '' ) {
		
		if ( ( defined('DOING_AJAX') && DOING_AJAX ) || isset( $_POST['gform_ajax'] ) ) {
			return $content;
		}
		
		$content = 'document.addEventListener( "DOMContentLoaded", function() { ';
		
		return $content;
		
	}
	
	

	function wrap_gform_cdata_close( $content = '' ) {
		
		if ( ( defined('DOING_AJAX') && DOING_AJAX ) || isset( $_POST['gform_ajax'] ) ) {
			return $content;
		}
		
		$content = ' }, false );';
		
		return $content;
	}		
	

	
	
	
	
	
	/**
	 *		Filters the image attributes before outputing
	 *		from wp_get_attachment_image
	 *
	 *		@since bric_v1.1
	 *
	 */
	
	function image_alt_tag( $attr, $attachment, $size ) {
		
		//Don't do anything if it's already populated
		if ( !empty( $attr['alt']) ) {
			return $attr;
		}
		
		//var_dump( $attachment );
		
		//Check for other text. First will be caption
		if ( !empty( $attachment->post_excerpt ) ) {
			
			$attr['alt'] = wp_trim_words( $attachment->post_excerpt );
			
		}
		//Fall back on the title, which we probably have
		else {
			
			$attr['alt'] = $attachment->post_title;
			
		}
		
		
		return $attr;
	}
	
	
 	
}


new BricFilters();