<?php


if (function_exists('acf_add_local_field_group')) :

	acf_add_local_field_group(array(
		'key' => 'group_63484feda7565',
		'title' => 'Block: Background Image',
		'fields' => array(
			array(
				'key' => 'field_63484fef2ced9',
				'label' => 'Background Image',
				'name' => 'background_image',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_6352c98fb6619',
				'label' => 'Triangle',
				'name' => 'triangle',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Show the color triangle in front of background image?',
				'default_value' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
				'ui' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/bg-image-block',
				),
			),
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/footer-block',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_6350350f71489',
		'title' => 'Block: Columns',
		'fields' => array(
			array(
				'key' => 'field_6350351086afe',
				'label' => 'Container',
				'name' => 'container',
				'aria-label' => '',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'no-container' => 'No Container',
					'container-fluid' => 'Container Fluid',
					'container' => 'Container',
					'container-xxl' => 'Container XXL',
					'container-xl' => 'Container XL',
					'container-lg' => 'Container LG',
					'container-md' => 'Container MD',
					'container-sm' => 'Container SM',
				),
				'default_value' => '',
				'return_format' => 'value',
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'layout' => 'vertical',
			),
			array(
				'key' => 'field_63cecf5ce1a04',
				'label' => 'Background Color Container',
				'name' => 'background_color_container',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'inside' => 'Inside',
					'outside' => 'Outside',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_63cfeac60fb59',
				'label' => 'Background Image',
				'name' => 'background_image',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_63cff246979d5',
				'label' => 'Background Size',
				'name' => 'background_size',
				'aria-label' => '',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_63cfeac60fb59',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'cover' => 'Cover',
					'contain' => 'Contain',
					'a-100' => '100% Height',
				),
				'default_value' => '',
				'return_format' => 'value',
				'allow_null' => 0,
				'other_choice' => 0,
				'layout' => 'vertical',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_63cff276979d6',
				'label' => 'Background Position',
				'name' => 'background_position',
				'aria-label' => '',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_63cfeac60fb59',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'center' => 'Center',
					'center-left' => 'Center Left',
					'center-right' => 'Center Ridge',
					'top-left' => 'Top Left',
					'top-right' => 'Top Right',
					'top-center' => 'Top Center',
					'bottom-left' => 'Bottom Left',
					'bottom-right' => 'Botton Right',
					'bottom-center' => 'Bottom Center',
				),
				'default_value' => '',
				'return_format' => 'value',
				'allow_null' => 0,
				'other_choice' => 0,
				'layout' => 'vertical',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_63cff2d0979d7',
				'label' => 'Background Repeat',
				'name' => 'background_repeat',
				'aria-label' => '',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_63cfeac60fb59',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'bg-image-no-repeat' => 'No Repeat',
					'bg-image-repeat' => 'Repeat',
				),
				'default_value' => '',
				'return_format' => 'value',
				'allow_null' => 0,
				'other_choice' => 0,
				'layout' => 'vertical',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_63cff6cc823c0',
				'label' => 'Overlay Percentage',
				'name' => 'overlay_percentage',
				'aria-label' => '',
				'type' => 'range',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_63cfeac60fb59',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'min' => 0,
				'max' => 100,
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/columns',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_634ed1d39da81',
		'title' => 'Block: Columns/Item',
		'fields' => array(
			array(
				'key' => 'field_634ed1d469786',
				'label' => 'Columns Per Row Mobile',
				'name' => 'columns_per_row_mobile',
				'aria-label' => '',
				'type' => 'range',
				'instructions' => '-1 means auto',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => -1,
				'max' => 12,
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_634ed1f369787',
				'label' => 'Columns Per Row Tablet',
				'name' => 'columns_per_row_tablet',
				'aria-label' => '',
				'type' => 'range',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => -1,
				'max' => 12,
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_634ed20e69788',
				'label' => 'Columns Per Row Large Screen',
				'name' => 'columns_per_row_large_screen',
				'aria-label' => '',
				'type' => 'range',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => -1,
				'max' => 12,
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/column-item',
				),
			),
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/columns',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_634dd609b02bc',
		'title' => 'Block: CTA',
		'fields' => array(
			array(
				'key' => 'field_634dd60a6b403',
				'label' => 'Call To Action',
				'name' => 'call_to_action',
				'aria-label' => '',
				'type' => 'link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/hero-header',
				),
			),
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/cta-row',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_634d7dc70056a',
		'title' => 'Block: Image',
		'fields' => array(
			array(
				'key' => 'field_634d7dc7293f3',
				'label' => 'Image',
				'name' => 'image',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'preview_size' => 'medium',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/content-image-row-block',
				),
			),
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/hero-header',
				),
			),
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/icon-card',
				),
			),
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/cta-row',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_63503a603ea7a',
		'title' => 'Block: Site Identity',
		'fields' => array(
			array(
				'key' => 'field_63503a617cfcd',
				'label' => 'Include',
				'name' => 'include',
				'aria-label' => '',
				'type' => 'checkbox',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'company_name' => 'Company Name',
					'address' => 'Address',
					'phone' => 'Phone',
					'email' => 'Email',
				),
				'default_value' => array(
					0 => 'company_name',
					1 => 'address',
					2 => 'phone',
					3 => 'email',
				),
				'return_format' => 'value',
				'allow_custom' => 0,
				'layout' => 'vertical',
				'toggle' => 0,
				'save_custom' => 0,
			),
			array(
				'key' => 'field_638f7f63f100d',
				'label' => 'Orientation',
				'name' => 'orientation',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'stacked' => 'Stacked',
					'wide' => 'Wide',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/site-identity',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));


	acf_add_local_field_group(array(
		'key' => 'group_635fea365d5aa',
		'title' => 'Block: Hero Header',
		'fields' => array(
			array(
				'key' => 'field_635feaf7e3c47',
				'label' => 'Minimum Height',
				'name' => 'minimum_height',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_635fea36807d7',
						'label' => 'Value',
						'name' => 'value',
						'aria-label' => '',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 25,
						'min' => 1,
						'max' => '',
						'placeholder' => '',
						'step' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_635fea65807d8',
						'label' => 'Units',
						'name' => 'units',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'px' => 'px',
							'%' => '%',
							'vw' => 'vw',
							'vh' => 'vh',
							'rem' => 'rem',
							'em' => 'em',
						),
						'default_value' => 'px',
						'return_format' => 'value',
						'multiple' => 0,
						'allow_null' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/hero-header',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));


	acf_add_local_field_group(array(
		'key' => 'group_63652cb727bcd',
		'title' => 'Block: Button',
		'fields' => array(
			array(
				'key' => 'field_63652cb7a0044',
				'label' => 'Link',
				'name' => 'link',
				'aria-label' => '',
				'type' => 'link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
			),
			array(
				'key' => 'field_63652cd8a0045',
				'label' => 'Download',
				'name' => 'download',
				'aria-label' => '',
				'type' => 'post_object',
				'instructions' => 'Use this to transform the button into a download for gated content using Download Monitor plugin.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'dlm_download',
				),
				'taxonomy' => '',
				'return_format' => 'object',
				'multiple' => 0,
				'allow_null' => 1,
				'ui' => 1,
			),
			array(
				'key' => 'field_63652dc0afeee',
				'label' => 'Theme Color',
				'name' => 'theme_color',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'none' => 'None',
					'primary' => 'Primary',
					'secondary' => 'Secondary',
					'tertiary' => 'Tertiary',
					'success' => 'Success',
					'danger' => 'Danger',
					'warning' => 'Warning',
					'info' => 'Info',
					'light' => 'Light',
					'dark' => 'Dark',
				),
				'default_value' => 'primary',
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_63652e4aa8564',
				'label' => 'Size',
				'name' => 'size',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'standard' => 'Standard',
					'sm' => 'Small',
					'lg' => 'Large',
				),
				'default_value' => 'standard',
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_63653806120db',
				'label' => 'Border',
				'name' => 'border',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => 'Add a border to a solid button. This won\'t have any effect on an outlined button.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'none' => 'None',
					'primary' => 'Primary',
					'secondary' => 'Secondary',
					'tertiary' => 'Tertiary',
					'success' => 'Success',
					'danger' => 'Danger',
					'warning' => 'Warning',
					'info' => 'Info',
					'light' => 'Light',
					'dark' => 'Dark',
					'white' => 'White',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/button',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));


	acf_add_local_field_group(array(
		'key' => 'group_63c996a4a9632',
		'title' => 'Block: Social Media',
		'fields' => array(
			array(
				'key' => 'field_63c996a40e8b4',
				'label' => 'Social Accounts',
				'name' => 'social_accounts',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => 'Select the icon you want for each social account',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_63c999429ebba',
						'label' => 'Account',
						'name' => 'account',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => 'If you don\'t see a social account listed, head over to Yoast SEO > Social to input your social accounts.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_63c996a40e8b4',
					),
					array(
						'key' => 'field_63c999749ebbb',
						'label' => 'icon',
						'name' => 'icon',
						'aria-label' => '',
						'type' => 'font-awesome',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'icon_sets' => array(
							0 => 'brands',
						),
						'custom_icon_set' => '',
						'default_label' => '',
						'default_value' => '',
						'save_format' => 'object',
						'allow_null' => 0,
						'show_preview' => 1,
						'enqueue_fa' => 0,
						'fa_live_preview' => '',
						'choices' => array(),
						'parent_repeater' => 'field_63c996a40e8b4',
					),
				),
			),
			array(
				'key' => 'field_63cad533d9a5a',
				'label' => 'Icon Size',
				'name' => 'icon_size',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => 'Icon size in px',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => '',
				'placeholder' => '',
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/social-media',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_63cadf8d05bb0',
		'title' => 'Block: Website Header',
		'fields' => array(
			array(
				'key' => 'field_63cadf8d4e832',
				'label' => 'Layout',
				'name' => 'layout',
				'aria-label' => '',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'row' => 'Inline',
					'column' => 'Stacked',
				),
				'default_value' => 'inline',
				'return_format' => 'value',
				'allow_null' => 0,
				'other_choice' => 0,
				'layout' => 'vertical',
				'save_other_choice' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/website-header',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));


	acf_add_local_field_group(array(
		'key' => 'group_63d34a5fa4f0f',
		'title' => 'Block: Menu',
		'fields' => array(
			array(
				'key' => 'field_63d34a5f8c684',
				'label' => 'Menu',
				'name' => 'wp_nav_menu',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					2 => 'Main Menu',
					4 => 'Policies',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_63d3547222ecb',
				'label' => 'Gap',
				'name' => 'gap',
				'aria-label' => '',
				'type' => 'range',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 3,
				'min' => 0,
				'max' => 5,
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_63d4079b792a1',
				'label' => 'Separator',
				'name' => 'separator',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/menu',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_63d353b1384b8',
		'title' => 'Block: Global Flex',
		'fields' => array(
			array(
				'key' => 'field_63d353b15a651',
				'label' => 'Flex Direction',
				'name' => 'flex_direction',
				'aria-label' => '',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'column' => 'Column',
					'row' => 'Row',
				),
				'default_value' => 'column',
				'return_format' => 'value',
				'allow_null' => 0,
				'other_choice' => 0,
				'layout' => 'vertical',
				'save_other_choice' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/column-item',
				),
			),
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/social-media',
				),
			),
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/menu',
				),
			),
		),
		'menu_order' => 50,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_63dd2179d0630',
		'title' => 'Block: Recent Posts',
		'fields' => array(
			array(
				'key' => 'field_63dd225651d7f',
				'label' => 'What To Show',
				'name' => 'what_to_show',
				'aria-label' => '',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'any' => 'Any Post Type',
					'post_type' => 'Like Post Type',
					'post' => 'Posts',
					'page' => 'Pages',
					'attachment' => 'Media',
					'podcast' => 'Podcasts',
					'staff' => 'Staff Members',
				),
				'default_value' => '',
				'return_format' => 'value',
				'allow_null' => 0,
				'other_choice' => 0,
				'layout' => 'vertical',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_63dd274ca4a11',
				'label' => 'Number of Posts',
				'name' => 'number_of_posts',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 5,
				'min' => '',
				'max' => '',
				'placeholder' => '',
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_63dd28c0db46b',
				'label' => 'List Style',
				'name' => 'list_style',
				'aria-label' => '',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'default' => 'Bullet',
					'none' => 'None',
				),
				'default_value' => '',
				'return_format' => 'value',
				'allow_null' => 0,
				'other_choice' => 0,
				'layout' => 'vertical',
				'save_other_choice' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/recent-posts',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_63dd2da734952',
		'title' => 'Block: Taxonomy Terms',
		'fields' => array(
			array(
				'key' => 'field_63dd2da733256',
				'label' => 'What to Show',
				'name' => 'what_to_show_tax',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'all' => 'All',
					'post_type' => 'Just for the current post type',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_63dd34f85e5ae',
				'label' => 'Taxonomy',
				'name' => 'taxonomy',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'category' => 'Categories',
					'post_tag' => 'Tags',
					'post_format' => 'Formats',
					'podcast_cat' => 'Categories',
					'position_class' => 'Position Types',
				),
				'default_value' => array(),
				'return_format' => 'value',
				'multiple' => 1,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_63dd30742b4c3',
				'label' => 'List Style',
				'name' => 'list_style',
				'aria-label' => '',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'default' => 'Bullet',
					'none' => 'None',
				),
				'default_value' => '',
				'return_format' => 'value',
				'allow_null' => 0,
				'other_choice' => 0,
				'layout' => 'vertical',
				'save_other_choice' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/taxonomy-terms',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));



	acf_add_local_field_group(array(
		'key' => 'group_63e11d3973acb',
		'title' => 'Block: CTA Image',
		'fields' => array(
			array(
				'key' => 'field_63e11d399413b',
				'label' => 'Image',
				'name' => 'image',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_63e11d4c9413c',
				'label' => 'Call To Action Link',
				'name' => 'cta',
				'aria-label' => '',
				'type' => 'link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
			),
			array(
				'key' => 'field_63e11e6af1a75',
				'label' => 'Overlay Opacity',
				'name' => 'overlay_opacity',
				'aria-label' => '',
				'type' => 'range',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => 0,
				'max' => 100,
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_63e11e89f1a76',
				'label' => 'Ratio',
				'name' => 'ratio',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Aspect ratio in format like 16:9',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '16:9',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/cta-image',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));






	acf_add_local_field_group(array(
		'key' => 'group_63cf41c5caa3c',
		'title' => 'Block: Accordion',
		'fields' => array(
			array(
				'key' => 'field_63cf48771abd5',
				'label' => 'Accordion Button Color',
				'name' => 'accordion_button_color_theme_color',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'default' => 'Default',
					'primary' => 'Primary',
					'secondary' => 'Secondary',
					'tertiary' => 'Tertiary',
					'quaternary' => 'Quaternary',
					'light' => 'Light',
					'dark' => 'Dark',
					'white' => 'White',
					'black' => 'Black',
					'transparent' => 'Transparent',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_63cf41c603836',
				'label' => 'Accordion Button Background',
				'name' => 'accordion_button_background_theme_color',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'default' => 'Default',
					'primary' => 'Primary',
					'secondary' => 'Secondary',
					'tertiary' => 'Tertiary',
					'quaternary' => 'Quaternary',
					'light' => 'Light',
					'dark' => 'Dark',
					'white' => 'White',
					'black' => 'Black',
					'transparent' => 'Transparent',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/accordion',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_63cee84bd441b',
		'title' => 'Block: Collapse',
		'fields' => array(
			array(
				'key' => 'field_63cee84c0c55f',
				'label' => 'Header/Button',
				'name' => 'header',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/collapse',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

endif;
