<?php


if (function_exists('acf_add_local_field_group')) :

	acf_add_local_field_group(array(
		'key' => 'group_63484feda7565',
		'title' => 'Block: Background Image',
		'fields' => array(
			array(
				'key' => 'field_63484fef2ced9',
				'label' => 'Background Image',
				'name' => 'background_image',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_6352c98fb6619',
				'label' => 'Triangle',
				'name' => 'triangle',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Show the color triangle in front of background image?',
				'default_value' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
				'ui' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/bg-image-block',
				),
			),
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/footer-block',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_6350350f71489',
		'title' => 'Block: Columns',
		'fields' => array(
			array(
				'key' => 'field_6350351086afe',
				'label' => 'Container',
				'name' => 'container',
				'aria-label' => '',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'no-container' => 'No Container',
					'container-fluid' => 'Container Fluid',
					'container' => 'Container',
					'container-xxl' => 'Container XXL',
					'container-xl' => 'Container XL',
					'container-lg' => 'Container LG',
					'container-md' => 'Container MD',
					'container-sm' => 'Container SM',
				),
				'default_value' => '',
				'return_format' => 'value',
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'layout' => 'vertical',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/columns',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_634ed1d39da81',
		'title' => 'Block: Columns/Item',
		'fields' => array(
			array(
				'key' => 'field_634ed1d469786',
				'label' => 'Columns Per Row Mobile',
				'name' => 'columns_per_row_mobile',
				'aria-label' => '',
				'type' => 'range',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => 0,
				'max' => 12,
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_634ed1f369787',
				'label' => 'Columns Per Row Tablet',
				'name' => 'columns_per_row_tablet',
				'aria-label' => '',
				'type' => 'range',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => 0,
				'max' => 12,
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_634ed20e69788',
				'label' => 'Columns Per Row Large Screen',
				'name' => 'columns_per_row_large_screen',
				'aria-label' => '',
				'type' => 'range',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => 0,
				'max' => 12,
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/column-item',
				),
			),
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/columns',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_634dd609b02bc',
		'title' => 'Block: CTA',
		'fields' => array(
			array(
				'key' => 'field_634dd60a6b403',
				'label' => 'Call To Action',
				'name' => 'call_to_action',
				'aria-label' => '',
				'type' => 'link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/hero-header',
				),
			),
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/cta-row',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_634d7dc70056a',
		'title' => 'Block: Image',
		'fields' => array(
			array(
				'key' => 'field_634d7dc7293f3',
				'label' => 'Image',
				'name' => 'image',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'preview_size' => 'medium',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/content-image-row-block',
				),
			),
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/hero-header',
				),
			),
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/icon-card',
				),
			),
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/cta-row',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_63503a603ea7a',
		'title' => 'Block: Site Identity',
		'fields' => array(
			array(
				'key' => 'field_63503a617cfcd',
				'label' => 'Include',
				'name' => 'include',
				'aria-label' => '',
				'type' => 'checkbox',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'company_name' => 'Company Name',
					'address' => 'Address',
					'phone' => 'Phone',
					'email' => 'Email',
				),
				'default_value' => array(
					0 => 'company_name',
					1 => 'address',
					2 => 'phone',
					3 => 'email',
				),
				'return_format' => 'value',
				'allow_custom' => 0,
				'layout' => 'vertical',
				'toggle' => 0,
				'save_custom' => 0,
			),
			array(
				'key' => 'field_638f7f63f100d',
				'label' => 'Orientation',
				'name' => 'orientation',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'stacked' => 'Stacked',
					'wide' => 'Wide',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/site-identity',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));


	acf_add_local_field_group(array(
		'key' => 'group_635fea365d5aa',
		'title' => 'Block: Hero Header',
		'fields' => array(
			array(
				'key' => 'field_635feaf7e3c47',
				'label' => 'Minimum Height',
				'name' => 'minimum_height',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_635fea36807d7',
						'label' => 'Value',
						'name' => 'value',
						'aria-label' => '',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 25,
						'min' => 1,
						'max' => '',
						'placeholder' => '',
						'step' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_635fea65807d8',
						'label' => 'Units',
						'name' => 'units',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'px' => 'px',
							'%' => '%',
							'vw' => 'vw',
							'vh' => 'vh',
							'rem' => 'rem',
							'em' => 'em',
						),
						'default_value' => 'px',
						'return_format' => 'value',
						'multiple' => 0,
						'allow_null' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/hero-header',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));


	acf_add_local_field_group(array(
		'key' => 'group_63652cb727bcd',
		'title' => 'Block: Button',
		'fields' => array(
			array(
				'key' => 'field_63652cb7a0044',
				'label' => 'Link',
				'name' => 'link',
				'aria-label' => '',
				'type' => 'link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
			),
			array(
				'key' => 'field_63652cd8a0045',
				'label' => 'Download',
				'name' => 'download',
				'aria-label' => '',
				'type' => 'post_object',
				'instructions' => 'Use this to transform the button into a download for gated content using Download Monitor plugin.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'dlm_download',
				),
				'taxonomy' => '',
				'return_format' => 'object',
				'multiple' => 0,
				'allow_null' => 1,
				'ui' => 1,
			),
			array(
				'key' => 'field_63652dc0afeee',
				'label' => 'Theme Color',
				'name' => 'theme_color',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'none' => 'None',
					'primary' => 'Primary',
					'secondary' => 'Secondary',
					'tertiary' => 'Tertiary',
					'success' => 'Success',
					'danger' => 'Danger',
					'warning' => 'Warning',
					'info' => 'Info',
					'light' => 'Light',
					'dark' => 'Dark',
				),
				'default_value' => 'primary',
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_63652e4aa8564',
				'label' => 'Size',
				'name' => 'size',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'standard' => 'Standard',
					'sm' => 'Small',
					'lg' => 'Large',
				),
				'default_value' => 'standard',
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_63653806120db',
				'label' => 'Border',
				'name' => 'border',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => 'Add a border to a solid button. This won\'t have any effect on an outlined button.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'none' => 'None',
					'primary' => 'Primary',
					'secondary' => 'Secondary',
					'tertiary' => 'Tertiary',
					'success' => 'Success',
					'danger' => 'Danger',
					'warning' => 'Warning',
					'info' => 'Info',
					'light' => 'Light',
					'dark' => 'Dark',
					'white' => 'White',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/button',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

endif;
